[package]
name = "fstdns"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "*"
env_logger = "*"
log = {version = "*", features = ["release_max_level_debug"]}
smart-default = "*"

tokio = {version = "1", features = ["macros", "rt", "io-util", "net", "time"]}
fst = "*"
socket2 = "*"

dns = { path = "../bbdnsp" }
misc = { path = "../misc" }

[target.'cfg(all(target_os = "linux", target_env = "gnu"))'.dependencies]
libc = "*"

[build-dependencies]
misc = { path = "../misc" }

[dev-dependencies]
rand = "*"
memory-stats = "1"

[profile.release]
lto = true
strip = true
